### ISSUE TITLE
Failed to setup turn 31. (Unit ID '136048556' was missing)

### ISSUE THREAD

**Issue by krabbenfreund** [DeamonHunter/AWBW-Replay-Player#135]
Hello,
I wanted to watch my replay with the (replay number: 969110), but I got the following error massage multiple times: 
"Failed to setup turn 31. (Unit ID '136048556' was missing)"

I tried the standard stuff like refreshing etc. but it does not help.

Is there any way how I can salvage the replay?

Here is the full error massage:

System.AggregateException: Failed to setup turn 31. (Unit ID '136048556' was missing)
 ---> AWBWApp.Game.Exceptions.ReplayMissingUnitException: Unit ID '136048556' was missing
   at AWBWApp.Game.API.Replay.Actions.EndTurnAction.SetupAndUpdate(ReplayController controller, ReplaySetupContext context)
   at AWBWApp.Game.Game.Logic.ReplayController.setupActions(Boolean logDesyncs)
   --- End of inner exception stack trace ---
   at AWBWApp.Game.Game.Logic.ReplayController.setupActions(Boolean logDesyncs)
   at AWBWApp.Game.Game.Logic.ReplayController.LoadReplay(ReplayData replayData, ReplayMap map)

**Comment by DeamonHunter** [comment]
Should be fixed in v0.11.5
