### ISSUE TITLE
Replay Viewer unable to support Games or Maps that use the new 17th Army Faction, "Azure Asteroid"

### ISSUE THREAD

**Issue by Xirema** [DeamonHunter/AWBW-Replay-Player#142]
Attempting to import maps that feature this faction crash the application, and attempting to import a game that features this faction will crash the application _and_ make it impossible to browse any of the already saved replays (the map + game data can be deleted manually to fix the application though).

I found the following stack trace in the runtime.log file, although I'm guessing it's just a microcosm of the more general "there's now a 17th army color that needs to be supported" issue:

```2024-04-29 20:40:08 [error]: An unhandled error has occurred.
2024-04-29 20:40:08 [error]: System.Collections.Generic.KeyNotFoundException: The given key '197' was not present in the dictionary.
2024-04-29 20:40:08 [error]: at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
2024-04-29 20:40:08 [error]: at AWBWApp.Game.Game.Tile.TerrainTileStorage.GetTileByAWBWId(Int32 id)
2024-04-29 20:40:08 [error]: at AWBWApp.Game.Game.Logic.CustomShoalGenerator.getTerrainTypeFromId(Int32 id)
2024-04-29 20:40:08 [error]: at AWBWApp.Game.Game.Logic.CustomShoalGenerator.getNearbyTiles(ReplayMap map, Int32 tileIndex, Int32 x, Int32 y)
2024-04-29 20:40:08 [error]: at AWBWApp.Game.Game.Logic.CustomShoalGenerator.CreateCustomShoalVersion(ReplayMap map)
2024-04-29 20:40:08 [error]: at AWBWApp.Game.UI.Editor.EditorGameMap.SetMap(ReplayMap map)
2024-04-29 20:40:08 [error]: at AWBWApp.Game.UI.Editor.EditorScreen.<>c__DisplayClass26_1.<LoadComplete>b__1()
2024-04-29 20:40:08 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2024-04-29 20:40:08 [error]: at osu.Framework.Threading.Scheduler.Update()
2024-04-29 20:40:08 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2024-04-29 20:40:08 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-04-29 20:40:08 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-04-29 20:40:08 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-04-29 20:40:08 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-04-29 20:40:08 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-04-29 20:40:08 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-04-29 20:40:08 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-04-29 20:40:08 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-04-29 20:40:08 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-04-29 20:40:08 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-04-29 20:40:08 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2024-04-29 20:40:08 [error]: at osu.Framework.Threading.GameThread.processFrame()
2024-04-29 20:40:08 [verbose]: [Notification] Adding new Notification: An error occured: An unhandled error has occurred.```

**Comment by DeamonHunter** [comment]
Oops forgot to mark this as done...
