### ISSUE TITLE
Failed to load replay

### ISSUE THREAD

**Issue by MMMajoor** [DeamonHunter/AWBW-Replay-Player#146]
I tried to load in an archive of the following game: https://awbw.amarriner.com/game.php?games_id=1284534

And now that I look again... It's the new army isn't it?

The application told my to click on the message and to paste this to the devs:

System.AggregateException: Failed to setup turn 2. (The given key '211' was not present in the dictionary.)
 ---> System.Collections.Generic.KeyNotFoundException: The given key '211' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at AWBWApp.Game.Game.Logic.ReplaySetupContext.UpdateBuildingAfterCapture(ReplayBuilding building, HashSet`1 teamsWhoSaw)
   at AWBWApp.Game.API.Replay.Actions.CaptureBuildingAction.SetupAndUpdate(ReplayController controller, ReplaySetupContext context)
   at AWBWApp.Game.Game.Logic.ReplayController.setupActions(Boolean logDesyncs)
   --- End of inner exception stack trace ---
   at AWBWApp.Game.Game.Logic.ReplayController.setupActions(Boolean logDesyncs)
   at AWBWApp.Game.Game.Logic.ReplayController.LoadReplay(ReplayData replayData, ReplayMap map)

**Comment by DeamonHunter** [comment]
Fixed by c4287b7d0f2e516f6aa22efd609f3391fd6f0d95.

Update to be out tomorrow.
